packages:
  - 'services/*'
  - 'shared/*'

injectWorkspacePackages: true

allowBuilds:
  '@prisma/client': true
  '@prisma/gusteaus': true
  bcrypt: true
  prisma: true
  protobufjs: true
  unrs-resolver: true

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/gusteaus'
  - bcrypt
  - prisma
  - protobufjs
  - unrs-resolver
