packages:
  - 'services/*'

injectWorkspacePackages: true

blockExoticSubdeps: false

allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  '@prisma/gusteaus': true
  bcrypt: true
  prisma: true
  protobufjs: true
  unrs-resolver: true
  "@shared/logger@git+https://github.com/beartrando/logger.git": true
  "@shared/errors@git+https://github.com/beartrando/errors.git": true
  "@shared/kafka-manager@git+https://github.com/beartrando/kafka-manager.git": true
  "@shared/grpc-client-manager@git+https://github.com/beartrando/grpc-client-manager.git": true
  "@shared/pg-boss-manager@git+https://github.com/beartrando/pg-boss-manager.git": true

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/gusteaus'
  - bcrypt
  - prisma
  - protobufjs
  - unrs-resolver
