// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.10
//   protoc               v3.21.12
// source: common/error.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "common.error";

export enum ErrorCode {
  UNKNOWN = 0,
  INVALID_SESSION = 1,
  ACCESS_DENIED = 2,
  NOT_FOUND = 3,
  VALIDATION_FAILED = 4,
  SERVICE_UNAVAILABLE = 5,
  INVALID_RESPONSE = 6,
  INVALID_AUTHORIZATION = 7,
  TOKEN_EXPIRED = 401,
  UNRECOGNIZED = -1,
}

export function errorCodeFromJSON(object: any): ErrorCode {
  switch (object) {
    case 0:
    case "UNKNOWN":
      return ErrorCode.UNKNOWN;
    case 1:
    case "INVALID_SESSION":
      return ErrorCode.INVALID_SESSION;
    case 2:
    case "ACCESS_DENIED":
      return ErrorCode.ACCESS_DENIED;
    case 3:
    case "NOT_FOUND":
      return ErrorCode.NOT_FOUND;
    case 4:
    case "VALIDATION_FAILED":
      return ErrorCode.VALIDATION_FAILED;
    case 5:
    case "SERVICE_UNAVAILABLE":
      return ErrorCode.SERVICE_UNAVAILABLE;
    case 6:
    case "INVALID_RESPONSE":
      return ErrorCode.INVALID_RESPONSE;
    case 7:
    case "INVALID_AUTHORIZATION":
      return ErrorCode.INVALID_AUTHORIZATION;
    case 401:
    case "TOKEN_EXPIRED":
      return ErrorCode.TOKEN_EXPIRED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return ErrorCode.UNRECOGNIZED;
  }
}

export function errorCodeToJSON(object: ErrorCode): string {
  switch (object) {
    case ErrorCode.UNKNOWN:
      return "UNKNOWN";
    case ErrorCode.INVALID_SESSION:
      return "INVALID_SESSION";
    case ErrorCode.ACCESS_DENIED:
      return "ACCESS_DENIED";
    case ErrorCode.NOT_FOUND:
      return "NOT_FOUND";
    case ErrorCode.VALIDATION_FAILED:
      return "VALIDATION_FAILED";
    case ErrorCode.SERVICE_UNAVAILABLE:
      return "SERVICE_UNAVAILABLE";
    case ErrorCode.INVALID_RESPONSE:
      return "INVALID_RESPONSE";
    case ErrorCode.INVALID_AUTHORIZATION:
      return "INVALID_AUTHORIZATION";
    case ErrorCode.TOKEN_EXPIRED:
      return "TOKEN_EXPIRED";
    case ErrorCode.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface ErrorObject {
  code: ErrorCode;
  details: string;
}

function createBaseErrorObject(): ErrorObject {
  return { code: 0, details: "" };
}

export const ErrorObject: MessageFns<ErrorObject> = {
  encode(message: ErrorObject, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.code !== 0) {
      writer.uint32(8).int32(message.code);
    }
    if (message.details !== "") {
      writer.uint32(18).string(message.details);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ErrorObject {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseErrorObject();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.code = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.details = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ErrorObject {
    return {
      code: isSet(object.code) ? errorCodeFromJSON(object.code) : 0,
      details: isSet(object.details) ? globalThis.String(object.details) : "",
    };
  },

  toJSON(message: ErrorObject): unknown {
    const obj: any = {};
    if (message.code !== 0) {
      obj.code = errorCodeToJSON(message.code);
    }
    if (message.details !== "") {
      obj.details = message.details;
    }
    return obj;
  },

  create(base?: DeepPartial<ErrorObject>): ErrorObject {
    return ErrorObject.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ErrorObject>): ErrorObject {
    const message = createBaseErrorObject();
    message.code = object.code ?? 0;
    message.details = object.details ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
