apiVersion: v1
kind: ConfigMap
metadata:
  name: gusteau-env
data:
  APP_NAME: "gusteau"
  APP_ENV: "prod"
  GRPC_PORT: "50051"

  DATABASE_URL: "postgresql://postgres:postgres@pgbouncer:6432/gusteau"
  DATABASE_DIRECT_URL: "postgresql://postgres:postgres@postgres:5432/gusteau"

  PG_BOSS_MAX: "5"
  PG_BOSS_MAINTENANCE_INTERVAL_SECONDS: "60"
  PG_BOSS_APPLICATION_NAME: "gusteau-pg-boss"

  KAFKA_BROKERS: "kafka:9092"
  KAFKA_CLIENT_ID: "gusteau-client"
  KAFKA_GROUP_ID: "gusteau-service"

  MESSAGE_CONSUMER_TOPIC_BATTLE_MATCHED: "battle.matched"
  MESSAGE_PRODUCER_TOPIC_BATTLE_UPDATED: "gusteau.battle_updated"
  MESSAGE_PRODUCER_TOPIC_BATTLE_STARTED: "gusteau.battle_started"
  MESSAGE_PRODUCER_TOPIC_BATTLE_TERMINATED: "gusteau.battle_finished"

  REDIS_HOST: "redis"
  REDIS_PORT: "6379"

  BATTLE_TURN_TIME_LIMIT: "21"
  BATTLE_START_TIME_LIMIT: "5"
