resources:
  - deployment.yaml
  - service.yaml
  - service-public.yaml
  - configmap.yaml
  - secret.yaml
  - ingress.yaml

images:
  - name: ghcr.io/beartrando/lenvora-streaming/service
    newTag: "dev"
