apiVersion: v1
kind: ConfigMap
metadata:
  name: remy-env
data:
  APP_NAME: "remy"
  APP_ENV: "prod"
  GRPC_PORT: "50051"

  HTTP_GATEWAY: "gateway:9090"
  WEBSOCKET_STREAMING: "streaming:8080"

  DATABASE_URL: "postgresql://postgres:postgres@pgbouncer:6432/remy"
  DATABASE_DIRECT_URL: "postgresql://postgres:postgres@postgres:5432/remy"

  KAFKA_BROKERS: "kafka:9092"
  KAFKA_CLIENT_ID: "remy-client"
  MESSAGE_CONSUMER_TOPIC_AI_CONNECTING_REQUEST: "remy.connecting-request"

  PG_BOSS_WEBSOCKET_SEND_EVENT: "pg-boss.websocket-send-event"
  PG_BOSS_MAX: "5"
  PG_BOSS_MAINTENANCE_INTERVAL_SECONDS: "60"
  PG_BOSS_APPLICATION_NAME: "remy-pg-boss"

  DEVICE_ID: "remy-device-id"
