name: Delete streaming service images

on:
  repository_dispatch:
    types:
      - cleanup-registry

run-name: "Cleanup registry - ${{ github.event.client_payload.service }}"

jobs:
  cleanup:
    runs-on: ubuntu-24.04

    permissions:
      packages: write

    steps:
      - name: Delete old streaming service images
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e

          KEEP_COUNT=30
          PROTECTED_TAGS="uat prod dev"

          gh api \
            --paginate \
            "/user/packages/container/tic-tac-toe-streaming%2Fservice/versions?per_page=${KEEP_COUNT}&page=2" 

          echo "=== Cleanup completed ==="