name: Cleanup registry

on:
  repository_dispatch:
    types:
      - cleanup-registry

run-name: "Cleanup registry - ${{ github.event.client_payload.service }}"

jobs:
  cleanup:
    runs-on: ubuntu-24.04

    permissions:
      packages: write

    steps:
      - name: Delete all profile service images
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e

          gh api \
            --paginate \
            --jq '.[].id' \
            "/user/packages/container/tic-tac-toe-profile/service/versions?per_page=100" |
          while read -r VERSION_ID; do
            echo "Deleting version: $VERSION_ID"

            gh api \
              --method DELETE \
              "/user/packages/container/tic-tac-toe-profile/service/versions/$VERSION_ID"
          done

          echo "=== All profile service images deleted ==="
          